import { Inter } from 'next/font/google';
import Link from 'next/link';
import { Provider } from '@/app/_components/provider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next sample',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ja'>
      <body className={inter.className}>
        <Provider>
          <h1>RootLayout</h1>
          <nav className='flex space-x-8 justify-center'>
            <Link href='/'>
              <div>TOP</div>
            </Link>
            <Link href='/with-footer'>
              <div>Footerありページ</div>
            </Link>
            <Link href='/without-footer'>
              <div>Footerなしページ</div>
            </Link>
            <Link href='/form'>
              <div>フォーム</div>
            </Link>
            <Link href='/todo/server-render'>
              <div>server-render</div>
            </Link>
            <Link href='/todo/client-render'>
              <div>client-render</div>
            </Link>
          </nav>
          {children}
        </Provider>
      </body>
    </html>
  );
}
